# Generated by Django 6.0.1 on 2026-05-25 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phase_introduced', models.IntegerField(blank=True, null=True)),
                ('alignment', models.CharField(blank=True, choices=[('Hero', 'Hero'), ('Villain', 'Villain'), ('Neutral', 'Neutral'), ('Reformed', 'Reformed'), ('Fallen', 'Fallen')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Alive', 'Alive'), ('Deceased', 'Deceased'), ('Unknown', 'Unknown')], max_length=100, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AlterEgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alter_egos', to='connections.character')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('characters', models.ManyToManyField(related_name='movies', to='connections.character')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current_member', models.BooleanField(default=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='connections.character')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='connections.team')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('Ally', 'Ally'), ('Enemy', 'Enemy'), ('Family', 'Family'), ('Romantic', 'Romantic'), ('Mentor', 'Mentor'), ('Variant', 'Variant')], max_length=100)),
                ('directional', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('character1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_character1', to='connections.character')),
                ('character2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_character2', to='connections.character')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character1', 'character2', 'relationship_type'), name='unique_relationship')],
            },
        ),
    ]
