# Generated by Django 6.0.1 on 2026-05-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='character',
            name='photo_path',
            field=models.CharField(blank=True, help_text='Path to a photo of the character.', max_length=500),
        ),
    ]
