# Generated by Django 6.0.1 on 2026-05-25 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_remove_character_photo_url_character_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='movie_introduced',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_characters', to='connections.movie'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('Ally', 'Ally'), ('Enemy', 'Enemy'), ('Family', 'Family'), ('Romantic', 'Romantic'), ('Mentor', 'Mentor'), ('Acquaintance', 'Acquaintance'), ('Variant', 'Variant'), ('Creation', 'Creation')], max_length=100),
        ),
    ]
