# Generated by Django 6.0.1 on 2026-05-25 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_character_movie_introduced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='latest_appearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_characters', to='connections.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='movies', to='connections.character'),
        ),
    ]
