# Generated by Django 6.0.1 on 2026-05-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_character_latest_appearance_alter_movie_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='earth_number',
            field=models.CharField(default='Earth-616', help_text='Earth number (e.g., Earth-616).', max_length=50),
        ),
    ]
