# Generated by Django 6.0.1 on 2026-05-27 01:48

import django.db.models.deletion
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_character_earth_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        # Add a temporary ForeignKey field, populate it from the existing CharField values,
        # then drop the old CharField and rename the temp field to `earth_number`.
        migrations.AddField(
            model_name='character',
            name='earth_number_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='connections.earth'),
        ),

        migrations.RunPython(
            code=lambda apps, schema_editor: (
                _populate_earth_fk(apps, schema_editor)
            ),
            reverse_code=migrations.RunPython.noop,
        ),

        migrations.RemoveField(
            model_name='character',
            name='earth_number',
        ),

        migrations.RenameField(
            model_name='character',
            old_name='earth_number_fk',
            new_name='earth_number',
        ),
    ]


def _populate_earth_fk(apps, schema_editor):
    Character = apps.get_model('connections', 'Character')
    Earth = apps.get_model('connections', 'Earth')

    # Create Earth records and assign FK for existing characters
    for char in Character.objects.all():
        # the old char field is still present until RemoveField runs, it's named 'earth_number'
        num = getattr(char, 'earth_number', None)
        if not num:
            continue
        earth_obj, _ = Earth.objects.get_or_create(number=num)
        # assign to the temporary FK field
        setattr(char, 'earth_number_fk_id', earth_obj.id)
        char.save(update_fields=['earth_number_fk_id'])
