# Generated by ChatGPT - create BulkAddConfig model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0006_earth_alter_character_earth_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkAddConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("default_rows", models.IntegerField(default=15)),
            ],
            options={
                "verbose_name": "Bulk Add Configuration",
                "verbose_name_plural": "Bulk Add Configuration",
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                apps.get_model('connections', 'BulkAddConfig').objects.get_or_create(
                    pk=1,
                    defaults={'default_rows': __import__('django.conf').conf.settings.CONNECTIONS_BULK_ADD_DEFAULT_ROWS}
                )
            ),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
