# Generated by Django 6.0.1 on 2026-06-07 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_create_bulkaddconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='latest_appearance',
        ),
    ]
