# Generated by Django 6.0.1 on 2026-08-06 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0008_remove_character_latest_appearance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('color', models.CharField(default='#8B5CF6', help_text="Hex color used for this lane's arrows and badge.", max_length=7)),
                ('lane_order', models.IntegerField(default=0, help_text='Left-to-right position of the lane.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide the lane without deleting it.')),
            ],
            options={
                'ordering': ('lane_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='WatchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('position', models.DecimalField(db_index=True, decimal_places=6, help_text='Sparse ordering key within the track. Leave blank to append to the end.', max_digits=20)),
                ('media_type', models.CharField(choices=[('Film', 'Film'), ('Series', 'Series'), ('Special', 'Special')], default='Film', max_length=20)),
                ('release_year', models.IntegerField(blank=True, help_text='Display only - never used for ordering.', null=True)),
                ('runtime_minutes', models.IntegerField(blank=True, help_text="Feeds the 'hours remaining' counter.", null=True)),
                ('episode_count', models.IntegerField(blank=True, help_text='For series, used with runtime as a per-episode figure.', null=True)),
                ('poster_path', models.CharField(blank=True, help_text='Static path to the poster, e.g. watch-order/iron-man.jpg. Blank renders a text card.', max_length=300)),
                ('note', models.TextField(blank=True, help_text='Shown in the detail card.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to keep the entry off the public chart.')),
                ('movie', models.ForeignKey(blank=True, help_text='Optional link to the same title in the character graph.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_entries', to='connections.movie')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Entries that must come first. Only needed for merges across tracks - order inside a single track comes from position.', related_name='unlocks', to='connections.watchentry')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='connections.watchtrack')),
            ],
            options={
                'verbose_name_plural': 'Watch entries',
                'ordering': ('track__lane_order', 'position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='connections.watchentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Watch progress',
                'constraints': [models.UniqueConstraint(fields=('user', 'entry'), name='unique_user_watch_entry')],
            },
        ),
        migrations.AddIndex(
            model_name='watchentry',
            index=models.Index(fields=['track', 'position'], name='watchentry_track_position'),
        ),
    ]
