# Generated by Django 6.0.1 on 2026-08-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0009_watchtrack_watchentry_watchprogress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Shown when this collection is selected.')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='watchentry',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Curated lists this belongs to. An entry can be in as many as you like.', related_name='entries', to='connections.watchcollection'),
        ),
    ]
