# Generated by Django 6.0.1 on 2026-08-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0010_watchcollection_watchentry_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchentry',
            name='tmdb_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Set automatically on the first lookup. Correct it by hand to fix a wrong match.', null=True),
        ),
        migrations.AddField(
            model_name='watchentry',
            name='tmdb_season',
            field=models.IntegerField(blank=True, help_text="For a single season of a series. Parsed from a title like 'Daredevil Season 1' when left blank; blank on a non-season title means the whole show.", null=True),
        ),
        migrations.AddField(
            model_name='watchentry',
            name='tmdb_type',
            field=models.CharField(blank=True, choices=[('movie', 'movie'), ('tv', 'tv')], help_text='Which TMDB endpoint this came from.', max_length=10),
        ),
    ]
