# Generated by Django 6.0.1 on 2026-08-06 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0011_watchentry_tmdb_id_watchentry_tmdb_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchtrack',
            name='continues_from',
            field=models.OneToOneField(blank=True, help_text='Pick the track this one carries on from, e.g. Multiverse Saga continues Infinity Saga. They share a column, stacked in order, chained end to start. Leave blank for a track that starts its own column.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continued_by', to='connections.watchtrack'),
        ),
    ]
