# Generated by Django 6.0.1 on 2026-08-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0012_watchtrack_continues_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchOrderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows_per_column', models.IntegerField(default=0, help_text='Wrap a lane into a fresh column once it reaches this many entries, so a long list reads across the page instead of running off the bottom. 0 disables wrapping and keeps one continuous column.')),
            ],
            options={
                'verbose_name': 'Watch Order Configuration',
                'verbose_name_plural': 'Watch Order Configuration',
            },
        ),
        migrations.AddField(
            model_name='watchentry',
            name='connects_to_previous',
            field=models.BooleanField(default=True, help_text='Uncheck to break the arrow coming in from the entry above. It still takes the next slot on the chart - only the arrow goes away.'),
        ),
    ]
