# Generated by Django 6.0.1 on 2026-08-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0013_watchorderconfig_watchentry_connects_to_previous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchorderconfig',
            name='rows_per_column',
        ),
        migrations.AddField(
            model_name='watchorderconfig',
            name='items_per_row',
            field=models.IntegerField(default=0, help_text='How many entries sit side by side before the list wraps onto the next row. The order reads left to right, then down, like a page of text. 0 disables wrapping and keeps one entry per row, running straight down.'),
        ),
    ]
