# Generated by Django 6.0.1 on 2026-02-03 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('lsb_number', models.CharField(blank=True, help_text='Lutheran Service Book number, if applicable.', max_length=10, null=True, unique=True)),
                ('ccli_number', models.CharField(blank=True, help_text='CCLI number, if applicable.', max_length=10, null=True, unique=True)),
                ('artist', models.ManyToManyField(blank=True, related_name='artist_songs', to='ministry.artist')),
                ('tag', models.ManyToManyField(blank=True, help_text='Tags for categorizing songs.', related_name='tagged_songs', to='ministry.tag')),
            ],
        ),
        migrations.CreateModel(
            name='SectionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('verse', 'Verse'), ('chorus', 'Chorus'), ('prechorus', 'Pre-Chorus'), ('bridge', 'Bridge'), ('tag', 'Tag'), ('intro', 'Intro'), ('outro', 'Outro'), ('instrumental', 'Instrumental')], max_length=20)),
                ('name', models.CharField(blank=True, help_text="Optional custom name for the section. E.g., 'Chorus', 'Verse 1'.", max_length=100, null=True)),
                ('lyrics', models.TextField(help_text='Lyrics for this section. Use line breaks to separate lines. Use double line breaks to separate slides.')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ministry.song')),
            ],
        ),
        migrations.CreateModel(
            name='ArrangementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order of this section in the arrangement.')),
                ('repeat_count', models.PositiveIntegerField(default=1, help_text='Number of times to repeat this section.')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrangement_items', to='ministry.sectiondefinition')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangement_items', to='ministry.song')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('song', 'order'), name='uniq_song_arrangement_order')],
            },
        ),
    ]
