# Generated by Django 6.0.1 on 2026-02-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='public_domain',
            field=models.BooleanField(default=False, help_text='Indicates if the song is in the public domain.'),
        ),
    ]
