# Generated by Django 6.0.1 on 2026-02-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0002_song_public_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sectiondefinition',
            name='section_type',
            field=models.CharField(choices=[('verse', 'Verse'), ('chorus', 'Chorus'), ('prechorus', 'Pre-Chorus'), ('bridge', 'Bridge'), ('tag', 'Tag'), ('intro', 'Intro'), ('outro', 'Outro'), ('instrumental', 'Instrumental')], default='verse', max_length=20),
        ),
    ]
