# Generated by Django 6.0.1 on 2026-02-03 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0003_alter_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangementitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangement_items', to='ministry.sectiondefinition'),
        ),
    ]
