# Generated by Django 6.0.1 on 2026-02-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0004_alter_arrangementitem_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bible_passage', models.CharField(blank=True, help_text='Bible passage reference for the devotion.', max_length=200, null=True)),
                ('content', models.TextField(help_text='Content of the devotion.')),
                ('date', models.DateField(help_text='Date of the devotion.')),
                ('embedded_media_url', models.URLField(blank=True, help_text='Optional URL for embedded media (e.g., YouTube video, Spotify Podcast).', null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
