# Generated by Django 6.0.1 on 2026-03-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0005_devotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(help_text="Description of the playlist, e.g., 'Songs for Lent 2026'.")),
                ('spotify_playlist_id', models.CharField(help_text='Spotify playlist ID for embedding.', max_length=50, unique=True)),
            ],
        ),
    ]
