# Generated by Django 6.0.1 on 2026-03-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0006_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='spotify_playlist_id',
            field=models.CharField(help_text='Spotify playlist ID for embedding.', max_length=100, unique=True),
        ),
    ]
