# Generated by Django 6.0.1 on 2026-06-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_aimodel_created_by_aiquirk_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='effort',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20),
        ),
    ]
