# Generated by Django 6.0.1 on 2026-02-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_private_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_performances',
            field=models.BooleanField(default=False),
        ),
    ]
