# Generated by Django 6.0.1 on 2026-03-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gpt_creator',
            field=models.BooleanField(default=False),
        ),
    ]
