# Generated by Django 6.0.1 on 2026-02-07 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PieceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('composer', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(default=True)),
                ('date_performed', models.DateField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('instrument', models.ManyToManyField(blank=True, to='rzpercussion.instrument')),
                ('performer', models.ManyToManyField(blank=True, to='rzpercussion.performer')),
                ('piece_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rzpercussion.piecetype')),
            ],
        ),
    ]
