# Generated by Django 6.0.1 on 2026-02-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzpercussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='super_private',
            field=models.BooleanField(default=False),
        ),
    ]
