# Generated by Django 6.0.1 on 2026-02-15 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the project.')),
                ('event', models.CharField(blank=True, help_text='The event or context for the project.', max_length=200)),
                ('date', models.DateField(blank=True, help_text='The date of the project or event.', null=True)),
                ('category', models.CharField(blank=True, help_text='The category or type of project.', max_length=100)),
                ('public', models.BooleanField(default=False, help_text='Whether the project is publicly visible.')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_source', models.CharField(max_length=200)),
                ('image_alt_text', models.CharField(blank=True, help_text='Alternative text for the image.', max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='development_portfolio.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tool_used',
            field=models.ManyToManyField(blank=True, help_text='Tools used in the project.', related_name='projects_using_tool', to='development_portfolio.tool'),
        ),
    ]
