# Generated by Django 6.0.1 on 2026-02-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_started', models.DateField(help_text='The date you started learning this skill.')),
            ],
            options={
                'ordering': ['-date_started'],
            },
        ),
    ]
