# Generated by Django 6.0.1 on 2026-02-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development_portfolio', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, help_text='A brief one-line description of the project.', max_length=300),
        ),
    ]
