# Generated by Django 6.0.1 on 2026-02-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development_portfolio', '0003_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True, help_text="URL to the project's code repository."),
        ),
    ]
