# Generated by Django 6.0.1 on 2026-02-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development_portfolio', '0004_project_repository_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='URL to the resource.')),
                ('description', models.TextField(blank=True, help_text='A brief description of the resource.')),
            ],
        ),
    ]
