# Generated by Django 6.0.1 on 2026-02-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development_portfolio', '0005_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='A brief description of the bot.')),
                ('repository_url', models.URLField(blank=True, help_text="URL to the bot's code repository.")),
                ('date_created', models.DateField(blank=True, help_text='The date the bot was created.', null=True)),
                ('date_retired', models.DateField(blank=True, help_text='The date the bot was retired.', null=True)),
            ],
        ),
    ]
