# Generated by Django 6.0.1 on 2026-03-12 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development_portfolio', '0006_bot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrudelProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, help_text='Strudel code or description of the project.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strudel_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
