# Generated by Django 6.0.1 on 2026-06-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development_portfolio', '0008_wheel_wheelitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='External URL to the deployed/live version of the project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url_name',
            field=models.CharField(blank=True, help_text="Django URL name for a project hosted on this site (e.g. 'dev-wheel'). Takes precedence over Live URL.", max_length=200),
        ),
    ]
